### ISSUE TITLE
[Usability Improvement] Unified Docker setup (Kerberized and non-Kerberized)

### ISSUE THREAD

**Issue by ravjotbrar** [vertica/spark-connector#183]
Proposed Improvements:
1. Increase User experience so new users can easily setup local environment for spark connector with options
 - Kerberized
2. Execute auto tests in CI for Kerberized environment

**Comment by jonathanl-bq** [comment]
Update:
- Currently have a Vertica container build that works, but cannot start up the database on build
- Best practice appears to be not to startup the server in the Dockerfile
- Next steps: try to override the entrypoint for the container and run a script in the Docker Compose file instead to startup and configure the database

**Comment by jonathanl-bq** [comment]
Update:
- I've switched focus to using Docker Compose to startup and configure the database, which significantly simplifies the whole setup
- The Database container is now fully configured
- Next steps: create KDC container, HDFS container, and client container

**Comment by jonathanl-bq** [comment]
Update:
- KDC container: Almost complete, running into error "Failed to get D-Bus connection: Operation not permitted". Root cause seems to be due to privileges. Tried adding option for that, but looks like image didn't rebuild, so testing that next.
- Vertica container: Done
- HDFS container: To do
- Client container: To do
- Testing the full configuration: To do
- CI integration: To do

**Comment by jonathanl-bq** [comment]
Update:
- Docker compose ended up being a problem, due to the previously mentioned privileges issue, and being unable to configure any services (can't run scripts after service starts, since that ties up the process; also still need to tie up process at end to keep container alive)
- Solution: I changed approach. Now I'm modifying our clientenv shell script to configure containers after running docker-compose.
- KDC container: Almost done, just a few minor permissions issues to resolve 
Vertica container: Almost done, just a few minor permissions issues to resolve
HDFS container: To do
Client container: To do
Testing the full configuration: To do
CI integration: To do

**Comment by jonathanl-bq** [comment]
Update:
KDC container: Done
Vertica container: Done
HDFS container: Should be just about done. Currently, the container stops running for some reason. I'm investigating ways to prevent this.
Client container: To do
Testing the full configuration: To do
CI integration: To do

**Comment by jonathanl-bq** [comment]
Update:
KDC container: Done
Vertica container: Done
HDFS container: Done
Client container: Done
Testing the full configuration: Working through some build errors. I expect this to take a bit more time, since there's likely to be other Kerberos related errors too.
CI integration: To do

**Comment by jonathanl-bq** [comment]
Update:
KDC container: Done
Vertica container: Done
HDFS container: Done
Client container: Done
Testing the full configuration: There are issues with the HDFS configuration, causing us to get this error:
Exception in thread "main" com.vertica.spark.util.error.ConnectorException: Error in communication with filestore. Check the 'staging_fs_url' parameter.
Caused by: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]

We'll be looking into this again on Monday over a call.
