### ISSUE TITLE
GitHub automation fails to move issues

### ISSUE THREAD

**Issue by Aryex** [vertica/spark-connector#487]
## Descriptions
Our two github actions, `auto-triage.yml` and `remove-issue.yml` currently doesn't work due to the usage of `GITHUB_TOKEN`. We previously used a personal token, which would expire and overall not recommended. We have since moved to using `GITHUB_TOKEN`. 

It seems however that it doesn't work, but the issue could be that the `GITHUB_TOKEN` does not have the necessary permissions.

About [`GITHUB_TOKEN` ](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)

**Comment by jeremyp-bq** [comment]
The settings for the GITHUB_TOKEN are set to read/write, but it still does not work.  According to [GitHub Actions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) that should provide read/write access to the issues, among other resources.

Perhaps we can try explicitly setting the read/write permission for issues on the jobs:
```
jobs:
  <my-job>:
    permissions:
      issues: write 
```

Otherwise we may be forced to go back to using a personal access token (not ideal).

**Comment by jeremyp-bq** [comment]
Adding explicit permissions did not work.  So we need to either go back to using a personal access token or find a different action that works with GITHUB_TOKEN.

Note for testing: After changes are made add a priority label (low. normal, or high) to an issue.  This should cause the Move labelled issue action to run.

**Comment by jeremyp-bq** [comment]
Since GITHUB_TOKEN does not work, and we don't want to use our our Personal Access Tokens, the best approach would probably be to create a service account in GitHub, add it as a member of the organization and/or contributor of the repo, then create and use a PAT from that service account.
